/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
//#include "N9H30.h"

#include "GUI.h"
#include "wm.h"
#include "DIALOG.h"
#include "math.h"
#include "stdio.h"
#include "stdlib.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
GUI_MEMDEV_Handle hNeedle;  // Handle to draw the needle bitmap
GUI_MEMDEV_Handle hScale;
GUI_MEMDEV_Handle hScaleRot;
GUI_MEMDEV_Handle hFIG4;
GUI_MEMDEV_Handle hFIG4Rot;

GUI_MEMDEV_Handle hFIG5;
GUI_MEMDEV_Handle hFIG5Rot;
GUI_MEMDEV_Handle hFIG6;
GUI_MEMDEV_Handle hFIG6Rot;

extern volatile int OS_TimeMS;


#define VehicleSpeed_PositionX 396
#define VehicleSpeed_PositionY 200


#define T_MAX           6000   // 7 sec
#define MAX_SPEED   140
#define T_MIN_FRAME_NEEDLE   30
#define T_MIN_FRAME  35   //45 //35


extern GUI_CONST_STORAGE GUI_BITMAP bmCluster_back_4;
extern GUI_CONST_STORAGE GUI_BITMAP _bmNeedle;


extern GUI_CONST_STORAGE GUI_BITMAP bmFIG4;
extern GUI_CONST_STORAGE GUI_BITMAP bmFIG5;
extern GUI_CONST_STORAGE GUI_BITMAP bmFIG6;


static void _DrawSpeed(int speed_idex)
{
    char ac[10];
    GUI_SetTextMode(GUI_TM_TRANS);
    GUI_SetTextAlign(GUI_TA_HCENTER | GUI_TA_VCENTER);

    GUI_SetFont(GUI_FONT_D64);
    GUI_SetColor(GUI_WHITE);
    sprintf(ac,"%d", speed_idex);
    GUI_DispStringHCenterAt(ac, VehicleSpeed_PositionX, VehicleSpeed_PositionY-12);
}

static void _DrawNeedle( int Angle, GUI_MEMDEV_Handle hDst)
{
    int xSizeNeedle, ySizeNeedle, xSizeDst, ySizeDst;
    I32 SinHQ, CosHQ;
    //
    // Draw needle
    //
    xSizeNeedle = GUI_MEMDEV_GetXSize(hNeedle);
    ySizeNeedle = GUI_MEMDEV_GetYSize(hNeedle);
    xSizeDst = (GUI_MEMDEV_GetXSize(hDst) + 1) & ~1;
    ySizeDst = (GUI_MEMDEV_GetYSize(hDst) + 1) & ~1;
    SinHQ = GUI__SinHQ((I32)((Angle) * (-1000)) + 90000);
    CosHQ = GUI__CosHQ((I32)((Angle) * (-1000)) + 90000);

    GUI_MEMDEV_RotateHQHR(hNeedle, hDst,
                          ((xSizeDst - xSizeNeedle) * 4) - (((xSizeNeedle) * CosHQ) >> 14),
                          ((ySizeDst - ySizeNeedle) * 4) + (((xSizeNeedle) * SinHQ) >> 14),
                          (int)((Angle) * (-1000) + 270000), 1000);

}

static int _CreateNeedle(void)
{
    if (hNeedle)
    {
        GUI_MEMDEV_Select(hNeedle);
        GUI_SetBkColor(GUI_TRANSPARENT);
        GUI_Clear();
        GUI_DrawBitmap(&_bmNeedle, 0, 0);
        GUI_MEMDEV_Select(0);
        return 0;
    }
    else
    {
        return 1;
    }
}

static void _DrawFIG4Speed(int speed_idex)
{
    char ac[10];
    GUI_SetTextMode(GUI_TM_TRANS);
    GUI_SetTextAlign(GUI_TA_HCENTER | GUI_TA_VCENTER);

    GUI_SetFont(GUI_FONT_D64);
    GUI_SetColor(GUI_WHITE);
    sprintf(ac,"%d", speed_idex);
    //GUI_DispStringHCenterAt(ac , VehicleSpeed_PositionX-180-28, VehicleSpeed_PositionY-12-20-116);
    GUI_DispStringHCenterAt(ac, VehicleSpeed_PositionX-208, VehicleSpeed_PositionY-12-136);
}

static void _DrawFIG4Needle( int Angle, GUI_MEMDEV_Handle hDst)
{
    int xSizeNeedle, ySizeNeedle, xSizeDst, ySizeDst;
    I32 SinHQ, CosHQ;
    //
    // Draw needle
    //
    xSizeNeedle = GUI_MEMDEV_GetXSize(hNeedle);
    ySizeNeedle = GUI_MEMDEV_GetYSize(hNeedle);
    xSizeDst =  384;     //440-28*2;
    ySizeDst =  208;          // 208;

    SinHQ = GUI__SinHQ((I32)((Angle) * (-1000)) + 90000);
    CosHQ = GUI__CosHQ((I32)((Angle) * (-1000)) + 90000);
    GUI_MEMDEV_RotateHQHR(hNeedle, hDst,
                          ((xSizeDst - xSizeNeedle) * 4) - (((xSizeNeedle) * CosHQ) >> 14),
                          ((ySizeDst - ySizeNeedle) * 4) + (((xSizeNeedle) * SinHQ) >> 14),
                          (int)((Angle) * (-1000) + 270000), 1000);
}

static void _DrawFIG5Speed(int speed_idex)
{
    char ac[10];
    GUI_SetTextMode(GUI_TM_TRANS);
    GUI_SetTextAlign(GUI_TA_HCENTER | GUI_TA_VCENTER);

    GUI_SetFont(GUI_FONT_D64);
    GUI_SetColor(GUI_WHITE);
    sprintf(ac,"%d", speed_idex);
    //GUI_DispStringHCenterAt(ac , VehicleSpeed_PositionX-180-28, VehicleSpeed_PositionY-12-20-28);
    GUI_DispStringHCenterAt(ac, VehicleSpeed_PositionX-208, VehicleSpeed_PositionY-12-48);
}

static void _DrawFIG5Needle( int Angle, GUI_MEMDEV_Handle hDst)
{
    int xSizeNeedle, ySizeNeedle, xSizeDst, ySizeDst;
    I32 SinHQ, CosHQ;
    //
    // Draw needle
    //
    xSizeNeedle = GUI_MEMDEV_GetXSize(hNeedle);
    ySizeNeedle = GUI_MEMDEV_GetYSize(hNeedle);
    xSizeDst = 384;  //440-28*2;
    ySizeDst = 384;  //440-28*2;

    SinHQ = GUI__SinHQ((I32)((Angle) * (-1000)) + 90000);
    CosHQ = GUI__CosHQ((I32)((Angle) * (-1000)) + 90000);
    GUI_MEMDEV_RotateHQHR(hNeedle, hDst,
                          ((xSizeDst - xSizeNeedle) * 4) - (((xSizeNeedle) * CosHQ) >> 14),
                          ((ySizeDst - ySizeNeedle) * 4) + (((xSizeNeedle) * SinHQ) >> 14),
                          (int)((Angle) * (-1000) + 270000), 1000);
}

static void _DrawFIG6Speed(int speed_idex)
{
    char ac[10];
    GUI_SetTextMode(GUI_TM_TRANS);
    GUI_SetTextAlign(GUI_TA_HCENTER | GUI_TA_VCENTER);

    GUI_SetFont(GUI_FONT_D64);
    GUI_SetColor(GUI_WHITE);
    sprintf(ac,"%d", speed_idex);
    //GUI_DispStringHCenterAt(ac , VehicleSpeed_PositionX-180-124, VehicleSpeed_PositionY-12-20);
    GUI_DispStringHCenterAt(ac, VehicleSpeed_PositionX-304, VehicleSpeed_PositionY-12-48);
}

static void _DrawFIG6Needle( int Angle, GUI_MEMDEV_Handle hDst)
{
    int xSizeNeedle, ySizeNeedle, xSizeDst, ySizeDst;
    I32 SinHQ, CosHQ;
    //
    // Draw needle
    //
    xSizeNeedle = GUI_MEMDEV_GetXSize(hNeedle);
    ySizeNeedle = GUI_MEMDEV_GetYSize(hNeedle);
    xSizeDst = 192;
    ySizeDst = 384;

    SinHQ = GUI__SinHQ((I32)((Angle) * (-1000)) + 90000);
    CosHQ = GUI__CosHQ((I32)((Angle) * (-1000)) + 90000);


    GUI_MEMDEV_RotateHQHR(hNeedle, hDst,
                          ((xSizeDst - xSizeNeedle) * 4) - (((xSizeNeedle) * CosHQ) >> 14),
                          ((ySizeDst - ySizeNeedle) * 4) + (((xSizeNeedle) * SinHQ) >> 14),
                          (int)((Angle) * (-1000) + 270000), 1000);
}



/*********************************************************************
*
*       _DrawScale
*/
static int _DrawScale (void)
{
    if (hScale)
    {
        GUI_MEMDEV_Select(hScale);
        GUI_SetBkColor(GUI_TRANSPARENT);
        GUI_Clear();
        GUI_DrawBitmap(&bmCluster_back_4, 0, 0);
        GUI_MEMDEV_Select(0);
        return 0;
    }
    else
    {
        return 1;
    }
}

static int _DrawFIG4Scale(void)
{
    if (hScale)
    {
        GUI_MEMDEV_Select(hFIG4);
        GUI_SetBkColor(GUI_TRANSPARENT);
        GUI_Clear();
        GUI_DrawBitmap(&bmFIG4, 0, 0);
        GUI_MEMDEV_Select(0);
        return 0;
    }
    else
    {
        return 1;
    }
}

static int _DrawFIG5Scale (void)
{
    if (hScale)
    {
        GUI_MEMDEV_Select(hFIG5);
        GUI_SetBkColor(GUI_TRANSPARENT);
        GUI_Clear();
        GUI_DrawBitmap(&bmFIG5, 0, 0);
        GUI_MEMDEV_Select(0);
        return 0;
    }
    else
    {
        return 1;
    }
}

static int _DrawFIG6Scale (void)
{
    if (hScale)
    {
        GUI_MEMDEV_Select(hFIG6);
        GUI_SetBkColor(GUI_TRANSPARENT);
        GUI_Clear();
        GUI_DrawBitmap(&bmFIG6, 0, 0);
        GUI_MEMDEV_Select(0);
        return 0;
    }
    else
    {
        return 1;
    }
}


void MainTask(void);

void MainTask(void)
{
    int speed, angle;
    float             f;
    int               t0;
    int               tStart;
    int               tDiff;
    int               tUsed;

    GUI_Init();

    WM_SetCreateFlags(WM_CF_MEMDEV);
    GUI_SetTextMode(GUI_TM_TRANS);

    hScale    = GUI_MEMDEV_CreateFixed32(0, 0, bmCluster_back_4.XSize, bmCluster_back_4.YSize);
    hScaleRot = GUI_MEMDEV_CreateFixed(0, 0, bmCluster_back_4.XSize, bmCluster_back_4.YSize, GUI_MEMDEV_NOTRANS, GUI_MEMDEV_APILIST_32, GUICC_M8888I);
    hNeedle   = GUI_MEMDEV_CreateFixed32(0, 0, _bmNeedle.XSize, _bmNeedle.YSize);
    hFIG4  = GUI_MEMDEV_CreateFixed32(0, 0, 258, 296);
    hFIG4Rot = GUI_MEMDEV_CreateFixed(0, 0, 258, 296, GUI_MEMDEV_NOTRANS, GUI_MEMDEV_APILIST_32, GUICC_M8888I);
    hFIG5  = GUI_MEMDEV_CreateFixed32(0, 0, 288, 240);
    hFIG5Rot = GUI_MEMDEV_CreateFixed(0, 0, 288, 240, GUI_MEMDEV_NOTRANS, GUI_MEMDEV_APILIST_32, GUICC_M8888I);
    hFIG6  = GUI_MEMDEV_CreateFixed32(0, 0, 288, 240);
    hFIG6Rot = GUI_MEMDEV_CreateFixed(0, 0, 288, 240, GUI_MEMDEV_NOTRANS, GUI_MEMDEV_APILIST_32, GUICC_M8888I);


    _CreateNeedle();
    _DrawScale();
    _DrawFIG4Scale();
    _DrawFIG5Scale();
    _DrawFIG6Scale();

    // Initialize high resolution anti aliasing
    //
    GUI_AA_EnableHiRes();
    GUI_AA_SetFactor(6);
    //
    // Create scale for rotation
    //
    speed = 0;
    angle = speed *2;
    GUI_MEMDEV_Select(hScaleRot);
    GUI_Clear();
    GUI_MEMDEV_Write(hScale);
    _DrawSpeed(speed);
    _DrawNeedle(angle, hScaleRot);
    GUI_MEMDEV_CopyToLCD(hScaleRot);
    GUI_MEMDEV_Select(0);

    while(1)
    {
        //
        // Accelerate and brake
        //
        t0 = GUI_GetTime();
        for (; (tDiff = GUI_GetTime() - t0) < T_MAX;)
        {
            tStart = GUI_GetTime();
            //
            // Calculate speed dependent on time
            //
            if (tDiff < (T_MAX >> 1))
            {
                f = 1 - (float)tDiff / (T_MAX >> 1);
                //f = f * f * f;
                f = f* f;
                speed = 140 - (140 * f);
            }
            else
            {
                f = 1 - ((float)tDiff - (T_MAX >> 1)) / (T_MAX >> 1);
                //f = f * f * f;
                f = f*f;
                speed = (140 * f);
            }
            angle = speed*2;

            //
            // Select clipping rectangle
            //

            if ((speed >= 0)  && (speed < 50))
            {
                GUI_MEMDEV_Select(hFIG4Rot);
                GUI_MEMDEV_WriteAt(hFIG4, 0, 0);
                _DrawFIG4Needle(angle,hFIG4Rot);
                _DrawFIG4Speed(speed);
                GUI_MEMDEV_CopyToLCDAt(hFIG4Rot,208, 136);
            }
            else if (speed >= 50 && speed < 90)
            {
                GUI_MEMDEV_Select(hFIG5Rot);
                GUI_MEMDEV_WriteAt(hFIG5, 0, 0);
                _DrawFIG5Needle(angle,hFIG5Rot);
                _DrawFIG5Speed(speed);
                GUI_MEMDEV_CopyToLCDAt(hFIG5Rot,208, 48);
                GUI_MEMDEV_Select(0);
            }
            else if (speed >= 90 && speed <=  140)
            {
                GUI_MEMDEV_Select(hFIG6Rot);
                GUI_MEMDEV_WriteAt(hFIG6, 0, 0);
                _DrawFIG6Needle(angle,hFIG6Rot);
                _DrawFIG6Speed(speed);
                GUI_MEMDEV_CopyToLCDAt(hFIG6Rot,304, 48);
                GUI_MEMDEV_Select(0);
            }

            tUsed = GUI_GetTime() - tStart;
            //sysprintf("delay=%d, %d\n",tUsed, speed);
            if (tUsed < T_MIN_FRAME)
            {
                GUI_X_Delay(T_MIN_FRAME - tUsed);
                //      sysprintf("delay=%d, %d\n",count, speed);
            }
        }
    }

}
