/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.10                          *
*        Compiled Dec 19 2019, 16:36:21                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <asm/ioctl.h>
#include <sys/mman.h>
#include <linux/fb.h>
#include <sys/time.h>
#include     <stdio.h>
#include     <stdlib.h>
#include     <unistd.h> 
#include     <stdint.h>
//#include     <sys/types.h>
#include     <sys/stat.h> 
#include     <fcntl.h> 
#include     <termios.h>  
#include     <errno.h>
#include     <string.h>
#include <signal.h>
#include    <pthread.h>
#include   <linux/serial.h>

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0             (GUI_ID_USER + 0x00)
#define ID_IMAGE_0             (GUI_ID_USER + 0x01)
#define ID_BUTTON_0             (GUI_ID_USER + 0x02)
#define ID_TEXT_0             (GUI_ID_USER + 0x03)
#define ID_DROPDOWN_0            (GUI_ID_USER + 0x04)
#define ID_TEXT_1            (GUI_ID_USER + 0x05)
#define ID_EDIT_0            (GUI_ID_USER + 0x06)
#define ID_BUTTON_1            (GUI_ID_USER + 0x07)
#define ID_DROPDOWN_1            (GUI_ID_USER + 0x08)
#define ID_TEXT_2            (GUI_ID_USER + 0x09)
#define ID_TEXT_3            (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2            (GUI_ID_USER + 0x0B)
#define ID_TEXT_4            (GUI_ID_USER + 0x0C)
#define ID_BUTTON_3            (GUI_ID_USER + 0x0D)
#define ID_TEXT_5            (GUI_ID_USER + 0x0E)
#define ID_BUTTON_4            (GUI_ID_USER + 0x0F)
#define ID_TEXT_6            (GUI_ID_USER + 0x10)
#define ID_BUTTON_5            (GUI_ID_USER + 0x11)
#define ID_TEXT_7    (GUI_ID_USER + 0x12)
#define ID_TEXT_8    (GUI_ID_USER + 0x13)
#define ID_TEXT_9    (GUI_ID_USER + 0x14)
#define ID_TEXT_10    (GUI_ID_USER + 0x15)
#define ID_TEXT_11    (GUI_ID_USER + 0x16)
#define ID_TEXT_12    (GUI_ID_USER + 0x17)
#define ID_TEXT_13    (GUI_ID_USER + 0x18)
#define ID_TEXT_14    (GUI_ID_USER + 0x19)

#define ID_IMAGE_0_IMAGE_0 0x00

// USER START (Optionally insert additional defines)
#define MSG_ANIMATE            (WM_USER + 0x02)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "BMP", ID_IMAGE_0_IMAGE_0
*/
static const U8 _acImage_0[463] = {
  0x42, 0x4D, 0xCE, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x90, 0x01, 0x00, 0x00, 0x12, 0x0B, 0x00, 0x00,
  0x12, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21,
  0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00,
  0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84,
  0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08,
  0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10,
  0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00,
  0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42,
  0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84,
  0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08,
  0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00,
  0x00,
};

// USER START (Optionally insert additional static data)
extern int g_SettingFlag;

static U8 s_au8Setting[700 * 1024];
static U8 s_au8SettingMenu[760 * 1024];

int SettingWiFiFlag;
int SettingEthernetFlag;
int SettingModbusFlag;
int SettingVNCFlag;

static WM_HWIN s_hKeyPad;

char g_au8CITY[256];

char g_buf0[4 * 1024];

static char buf[1024];

extern U8 g_chSSID[1024];
extern U8 g_chPSK[1024];
int g_SettingWiFiFlag;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SettingMenu", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "SettingBackground", ID_IMAGE_0, 0, 0, 800, 480, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 0, 0, 64, 64, 0, 0x0, 1 },
  { TEXT_CreateIndirect, "SettingSSID", ID_TEXT_0, 190, 6, 80, 32, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect, "SSID2", ID_DROPDOWN_0, 273, 6, 412, 370, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SettingPWD", ID_TEXT_1, 190, 52, 80, 32, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "PWD2", ID_EDIT_0, 273, 52, 412, 37, 0, 0x0100, 0 },
  { BUTTON_CreateIndirect, "SettingConnect", ID_BUTTON_1, 700, 0, 100, 100, 0, 0x0, 2 },
  { DROPDOWN_CreateIndirect, "CITY2", ID_DROPDOWN_1, 0, 129, 200, 370, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CITY", ID_TEXT_2, 0, 90, 200, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "WiFi", ID_TEXT_3, 0, 200, 200, 32, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "WiFi2", ID_BUTTON_2, 50, 228, 98, 59, 0, 0x0, 3 },
  { TEXT_CreateIndirect, "Ethernet", ID_TEXT_4, 0, 297, 200, 32, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Ethernet2", ID_BUTTON_3, 50, 326, 98, 59, 0, 0x0, 4 },
  { TEXT_CreateIndirect, "Modbus", ID_TEXT_5, 292, 200, 200, 32, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Modbus2", ID_BUTTON_4, 340, 228, 98, 59, 0, 0x0, 5 },
  { TEXT_CreateIndirect, "VNC", ID_TEXT_6, 292, 297, 200, 32, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "VNC2", ID_BUTTON_5, 340, 326, 98, 59, 0, 0x0, 6 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_7, 153, 243, 60, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_8, 0, 243, 50, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_9, 154, 344, 60, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_10, 0, 340, 50, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_11, 443, 243, 60, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_12, 287, 243, 50, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_13, 443, 344, 60, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_14, 287, 340, 50, 32, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize) {
  switch (Id) {
  case ID_IMAGE_0_IMAGE_0:
    *pSize = sizeof(_acImage_0);
    return (const void *)_acImage_0;
  }
  return NULL;
}

// USER START (Optionally insert additional static code)
extern U32 NVT_Load_File(char * pchFileName, U8 * pu8Buffer);

extern WM_HWIN GUI_CreateKeyPad(WM_HWIN hParent);

void NVT_Load_File2(char * szFileName, int x, int y)
{
    FILE * file_fd;
    I32 FileSize;

    file_fd = NULL;
    file_fd = fopen(szFileName, "rb");
    if (file_fd == NULL)
    {
        printf("### fopen fail!");
        return;
    }
    fseek(file_fd, 0, SEEK_END);
    FileSize = ftell(file_fd);
    fseek(file_fd, 0, SEEK_SET);
    FileSize = fread(s_au8Setting, 1, FileSize, file_fd);
    if (FileSize == -1)
    {
        fclose(file_fd);
        printf("### fread fail!");
        return;
    }
    fclose(file_fd);
//    GUI_BMP_Draw(s_au8BMP, x, y);
    GUI_DrawStreamedBitmapAuto(s_au8Setting, x, y);
//    GUI_JPEG_Draw(s_au8BMP, i32FileSize, x, y);
}

static int _ButtonSkin(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    int Index;
    WM_HWIN hWin;

    hWin = pDrawItemInfo->hWin;
    BUTTON_GetUserData(hWin, &Index, sizeof(Index));

    switch (pDrawItemInfo->Cmd)
    {
    case WIDGET_ITEM_DRAW_BACKGROUND:
        //GUI_SetBkColor(0x00ABBCC5);
        //GUI_SetBkColor(GUI_YELLOW);
        //GUI_Clear();
        break;
    case WIDGET_ITEM_DRAW_BITMAP:
        if (Index == 1)
            NVT_Load_File2("/mnt/dta/back1.dta", 0, 0);
        else if (Index == 2)
            NVT_Load_File2("/mnt/dta/on1.dta", 0, 0);
        else if (Index == 3)
        {
            if (SettingWiFiFlag == 0)
                NVT_Load_File2("/mnt/dta/off1.dta", 0, 0);
            else
                NVT_Load_File2("/mnt/dta/on1.dta", 0, 0);
        }
        else if (Index == 4)
        {
            if ((SettingEthernetFlag == 0) || (SettingEthernetFlag == 3)) // FIXME
            {
                SettingEthernetFlag = 0;
                NVT_Load_File2("/mnt/dta/off1.dta", 0, 0);
            }
            else
                NVT_Load_File2("/mnt/dta/on1.dta", 0, 0);
        }
        else if (Index == 5)
        {
            if ((SettingModbusFlag == 0) || (SettingModbusFlag == 3)) // FIXME
            {
                SettingModbusFlag = 0;
                NVT_Load_File2("/mnt/dta/off1.dta", 0, 0);
            }
            else
                NVT_Load_File2("/mnt/dta/on1.dta", 0, 0);
        }
        else if (Index == 6)
        {
            if (SettingVNCFlag == 0)
                NVT_Load_File2("/mnt/dta/off1.dta", 0, 0);
            else
                NVT_Load_File2("/mnt/dta/on1.dta", 0, 0);
        }
        break;
    }
    return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
    int i, j, k;
    WM_MESSAGE     Message;
    FILE *pstream;

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'SettingBackground'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    FileSize = NVT_Load_File("/mnt/dta/setting_menu.dta", s_au8SettingMenu);
    IMAGE_SetDTA(hItem, s_au8SettingMenu, FileSize);
    //
    // Initialization of 'SettingSSID'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "SSID:");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'SSID2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetFont(hItem, GUI_FONT_32B_ASCII);
    DROPDOWN_AddString(hItem, "Select SSID");
    DROPDOWN_SetAutoScroll(hItem, 1);
    DROPDOWN_SetScrollbarWidth(hItem, 32);
    //
    // Initialization of 'SettingPWD'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "PWD:");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'PWD2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem, GUI_FONT_32B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'SettingConnect'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    BUTTON_SetText(hItem, "Connect");
    //
    // Initialization of 'CITY2'
    //
    //sprintf(g_au8CITY, "%s", "hsinchu");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_AddString(hItem, "hsinchu");
    DROPDOWN_AddString(hItem, "taipei");
    DROPDOWN_AddString(hItem, "SHENGZHEN");
    DROPDOWN_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'CITY'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Weather CITY");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'WiFi'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "WiFi");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Ethernet'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Ethernet");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Modbus'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Modbus");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'VNC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "VNC");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "OFF");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "ON");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "OFF");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "ON");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "OFF");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "ON");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "OFF");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "ON");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    // USER START (Optionally insert additional code for further widget initialization)
        #if 1 // FIXME
        memset(g_buf0, 0x00, 4*1024);
        pstream = popen("wpa_cli -i wlan0 scan", "r");
        fread(g_buf0, 1, 4*1024, pstream);
        printf("### sr=%s ###\n", g_buf0);
        pclose(pstream);
        memset(g_buf0, 0x00, 4*1024);
        pstream = popen("wpa_cli -i wlan0 scan_results", "r");
        fread(g_buf0, 1, 4*1024, pstream);
        printf("### sr=%s ###\n", g_buf0);
        pclose(pstream);
        #endif
        #if 1 // FIXME
        hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
        i = 49;
        for (k=0; k<20; k++)
        {
        for (; i<1024; i++)
        {
            if (g_buf0[i] != 0x09)
            {
                //printf("1 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        for (; i<1024; i++)
        {
            if (g_buf0[i] == 0x09)
            {
                //printf("2 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        for (; i<1024; i++)
        {
            if (g_buf0[i] != 0x09)
            {
                //printf("3 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        for (; i<1024; i++)
        {
            if (g_buf0[i] == 0x09)
            {
                //printf("4 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        for (; i<1024; i++)
        {
            if (g_buf0[i] != 0x09)
            {
                //printf("5 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        for (; i<1024; i++)
        {
            if (g_buf0[i] == 0x09)
            {
                //printf("6 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        for (; i<1024; i++)
        {
            if (g_buf0[i] != 0x09)
            {
                //printf("7 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        for (; i<1024; i++)
        {
            if (g_buf0[i] == 0x09)
            {
                //printf("8 %c", g_buf0[i]);
                continue;
            }
            else
                break;
        }
        j = 0;
        for (; i<1024; i++)
        {
            if (g_buf0[i] != 0x09)
                buf[j] = g_buf0[i];
            else
                break;
            if (buf[j] == 0x0A)
            {
                buf[j] = 0x00;
                break;
            }
            j++;
        }
        DROPDOWN_AddString(hItem, buf);
        }
        #endif

        i = 1;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &i, sizeof(i));

        i = 3;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &i, sizeof(i));

        i = 4;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &i, sizeof(i));

        i = 5;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &i, sizeof(i));

        i = 6;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &i, sizeof(i));

        s_hKeyPad = GUI_CreateKeyPad(pMsg->hWin);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            g_SettingFlag = 2;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'SSID2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
            memset(g_chSSID, 0x00, 1024);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
            DROPDOWN_GetItemText(hItem, DROPDOWN_GetSel(hItem), g_chSSID, 1024);
            printf("### dd0=%s ###\n", g_chSSID);

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'PWD2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            Message.Data.v = 1;  // 1 stand for show keypad
            Message.hWin   = s_hKeyPad;
            Message.MsgId  = MSG_ANIMATE;
            WM_SendMessage(s_hKeyPad, &Message);

        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'SettingConnect'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
            EDIT_GetText(hItem, g_chPSK, 256);
            printf("### s=%s %x, p=%s ###\n", g_chSSID, g_chSSID[0], g_chPSK);
            if (g_chSSID[0] == 0x00)
                g_SettingWiFiFlag = 0;
            else
                g_SettingWiFiFlag = 1;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'CITY2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
            DROPDOWN_GetItemText(hItem, DROPDOWN_GetSel(hItem), g_au8CITY, 256);
            printf("### dd1=%s ###\n", g_au8CITY);

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'WiFi2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            SettingWiFiFlag ^= 1;
            #if 0 // FIXME
            SettingWiFiFlag2 = 1;
            #endif

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Ethernet2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            SettingEthernetFlag ^= 1;
            #if 0 // FIXME
            SettingEthernetFlag2 = 1;
            #endif

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Modbus2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            SettingModbusFlag ^= 1;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'VNC2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            SettingVNCFlag ^= 1;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSettingMenu
*/
WM_HWIN CreateSettingMenu(void);
WM_HWIN CreateSettingMenu(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/


