/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.10                          *
*        Compiled Dec 19 2019, 16:36:21                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <asm/ioctl.h>
#include <sys/mman.h>
#include <linux/fb.h>
#include <sys/time.h>
#include     <stdio.h>
#include     <stdlib.h>
#include     <unistd.h> 
#include     <stdint.h>
//#include     <sys/types.h>
#include     <sys/stat.h> 
#include     <fcntl.h> 
#include     <termios.h>  
#include     <errno.h>
#include     <string.h>
#include <signal.h>
#include    <pthread.h>
#include   <linux/serial.h>

// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_BUTTON_1    (GUI_ID_USER + 0x02)
#define ID_BUTTON_2    (GUI_ID_USER + 0x03)
#define ID_BUTTON_3    (GUI_ID_USER + 0x04)
#define ID_IMAGE_0    (GUI_ID_USER + 0x05)
#define ID_IMAGE_1    (GUI_ID_USER + 0x06)
#define ID_IMAGE_2    (GUI_ID_USER + 0x07)
#define ID_IMAGE_3    (GUI_ID_USER + 0x08)
#define ID_TEXT_0    (GUI_ID_USER + 0x09)
#define ID_TEXT_1    (GUI_ID_USER + 0x0A)
#define ID_TEXT_2    (GUI_ID_USER + 0x0B)
#define ID_TEXT_3    (GUI_ID_USER + 0x0C)

#define ID_IMAGE_0_IMAGE_0  0x00
#define ID_IMAGE_1_IMAGE_0  0x01
#define ID_IMAGE_2_IMAGE_0  0x02
#define ID_IMAGE_3_IMAGE_0  0x03

// USER START (Optionally insert additional defines)
#define MSG_ANIMATE1            (WM_USER + 0x02)
#define MSG_ANIMATE2            (WM_USER + 0x03)
#define MSG_ANIMATE3            (WM_USER + 0x04)
#define ANIMATION_TIME         300

typedef struct {
  WM_HWIN hWin;
  WM_HWIN hBackButton;
  int     Dir;
} ANIM_DATA;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _acImage_0, "BMP", ID_IMAGE_0_IMAGE_0
*/
static const U8 _acImage_0[463] = {
  0x42, 0x4D, 0xCE, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x90, 0x01, 0x00, 0x00, 0x12, 0x0B, 0x00, 0x00,
  0x12, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21,
  0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00,
  0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84,
  0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08,
  0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10,
  0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00,
  0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42,
  0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84,
  0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08,
  0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00,
  0x00,
};

/*********************************************************************
*
*       _acImage_1, "BMP", ID_IMAGE_1_IMAGE_0
*/
static const U8 _acImage_1[463] = {
  0x42, 0x4D, 0xCE, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x90, 0x01, 0x00, 0x00, 0x12, 0x0B, 0x00, 0x00,
  0x12, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21,
  0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00,
  0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84,
  0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08,
  0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10,
  0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00,
  0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42,
  0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84,
  0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08,
  0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00,
  0x00,
};

/*********************************************************************
*
*       _acImage_2, "BMP", ID_IMAGE_2_IMAGE_0
*/
static const U8 _acImage_2[463] = {
  0x42, 0x4D, 0xCE, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x90, 0x01, 0x00, 0x00, 0x12, 0x0B, 0x00, 0x00,
  0x12, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21,
  0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00,
  0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84,
  0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08,
  0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10,
  0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00,
  0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42,
  0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84,
  0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08,
  0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00,
  0x00,
};

// USER START (Optionally insert additional static data)
static GUI_ANIM_HANDLE hAnim1;
static GUI_ANIM_HANDLE hAnim2;
static GUI_ANIM_HANDLE hAnim3;
static ANIM_DATA       AnimData1;
static ANIM_DATA       AnimData2;
static ANIM_DATA       AnimData3;
static WM_HWIN hTempMenu;
static WM_HWIN hDateMenu;
static WM_HWIN hWeatherMenu;

static U8 s_au8MainMenu[760 * 1024];
static U8 s_au8Menu1[130 * 1024];
static U8 s_au8Menu2[130 * 1024];
static U8 s_au8Menu3[130 * 1024];
static U8 s_au8Heading[10 * 1024];
static U8 s_au8Eth[10 * 1024];
static U8 s_au8WiFi[10 * 1024];
static U8 s_au8WeatherWeather[10 * 1024];

int g_SettingFlag;

extern int SettingWiFiFlag;
extern int SettingEthernetFlag;
extern int SettingModbusFlag;
extern int SettingVNCFlag;

static char s_buf0[1024];
//char g_buf0[4 * 1024];

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "MainMenu", ID_IMAGE_0, 0, 0, 800, 480, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Temp-", ID_BUTTON_0, 8, 72, 64, 64, 0, 0x0, 1 },
  { BUTTON_CreateIndirect, "Temp+", ID_BUTTON_1, 200, 72, 64, 64, 0, 0x0, 2 },
  { BUTTON_CreateIndirect, "TempLoop", ID_BUTTON_2, 105, 408, 64, 64, 0, 0x0, 3 },
  { BUTTON_CreateIndirect, "Set", ID_BUTTON_3, 728, 8, 32, 32, 0, 0x0, 4 },
  { IMAGE_CreateIndirect, "Heading", ID_IMAGE_1, 350, 8, 100, 44, 0, 0, 0 },
  { IMAGE_CreateIndirect, "WiFi", ID_IMAGE_2, 584, 8, 32, 32, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Eth", ID_IMAGE_3, 656, 8, 32, 32, 0, 0, 0 },
  { TEXT_CreateIndirect, "Temp1", ID_TEXT_0, 56, 72, 80, 64, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Temp2", ID_TEXT_1, 136, 99, 51, 39, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "IP1", ID_TEXT_2, 580, 416, 220, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "IP2", ID_TEXT_3, 580, 448, 220, 32, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize) {
  switch (Id) {
  case ID_IMAGE_0_IMAGE_0:
    *pSize = sizeof(_acImage_0);
    return (const void *)_acImage_0;
  case ID_IMAGE_1_IMAGE_0:
    *pSize = sizeof(_acImage_1);
    return (const void *)_acImage_1;
  case ID_IMAGE_2_IMAGE_0:
    *pSize = sizeof(_acImage_2);
    return (const void *)_acImage_2;
  case ID_IMAGE_3_IMAGE_0:
    *pSize = sizeof(_acImage_2);
    return (const void *)_acImage_2;
  }
  return NULL;
}

// USER START (Optionally insert additional static code)
static void _AnimateWin1(GUI_ANIM_INFO * pInfo, void * pVoid) {
  int         yPos;
  ANIM_DATA * pData;

  pData = (ANIM_DATA *)pVoid;
  if (pData->Dir) {
    yPos = (LCD_GetYSize() - 256) + ((256 * pInfo->Pos) / GUI_ANIM_RANGE);
  } else {
    yPos = LCD_GetYSize() - ((256 * pInfo->Pos) / GUI_ANIM_RANGE);
  }
  WM_MoveTo(pData->hWin,    8, yPos-80);
}

static void _AnimateWin2(GUI_ANIM_INFO * pInfo, void * pVoid) {
  int         yPos;
  ANIM_DATA * pData;

  pData = (ANIM_DATA *)pVoid;
  if (pData->Dir) {
    yPos = (LCD_GetYSize() - 256) + ((256 * pInfo->Pos) / GUI_ANIM_RANGE);
  } else {
    yPos = LCD_GetYSize() - ((256 * pInfo->Pos) / GUI_ANIM_RANGE);
  }
  WM_MoveTo(pData->hWin,    272, yPos-144);
}

static void _AnimateWin3(GUI_ANIM_INFO * pInfo, void * pVoid) {
  int         yPos;
  ANIM_DATA * pData;

  pData = (ANIM_DATA *)pVoid;
  if (pData->Dir) {
    yPos = (LCD_GetYSize() - 256) + ((256 * pInfo->Pos) / GUI_ANIM_RANGE);
  } else {
    yPos = LCD_GetYSize() - ((256 * pInfo->Pos) / GUI_ANIM_RANGE);
  }
  WM_MoveTo(pData->hWin,    536, yPos-72);
}

static void _AnimateDelete1(void * pVoid) {
  ANIM_DATA * pData;

  pData = (ANIM_DATA *)pVoid;
  pData->Dir ^= 1;
}

static void _AnimateDelete2(void * pVoid) {
  ANIM_DATA * pData;

  pData = (ANIM_DATA *)pVoid;
  pData->Dir ^= 1;
}

static void _AnimateDelete3(void * pVoid) {
  ANIM_DATA * pData;

  pData = (ANIM_DATA *)pVoid;
  pData->Dir ^= 1;
}

static void _AnimateCreate1(GUI_ANIM_HANDLE * pAnim, ANIM_DATA * pAnimData) {
  *pAnim = GUI_ANIM_Create(ANIMATION_TIME, 10, (void *)pAnimData, 0);
  GUI_ANIM_AddItem(*pAnim, 0, ANIMATION_TIME, ANIM_ACCELDECEL, (void *)pAnimData, _AnimateWin1);
  GUI_ANIM_StartEx(*pAnim, 1, _AnimateDelete1);
}

static void _AnimateCreate2(GUI_ANIM_HANDLE * pAnim, ANIM_DATA * pAnimData) {
  *pAnim = GUI_ANIM_Create(ANIMATION_TIME, 10, (void *)pAnimData, 0);
  GUI_ANIM_AddItem(*pAnim, 0, ANIMATION_TIME, ANIM_ACCELDECEL, (void *)pAnimData, _AnimateWin2);
  GUI_ANIM_StartEx(*pAnim, 1, _AnimateDelete2);
}

static void _AnimateCreate3(GUI_ANIM_HANDLE * pAnim, ANIM_DATA * pAnimData) {
  *pAnim = GUI_ANIM_Create(ANIMATION_TIME, 10, (void *)pAnimData, 0);
  GUI_ANIM_AddItem(*pAnim, 0, ANIMATION_TIME, ANIM_ACCELDECEL, (void *)pAnimData, _AnimateWin3);
  GUI_ANIM_StartEx(*pAnim, 1, _AnimateDelete3);
}

U32 NVT_Load_File(char * pchFileName, U8 * pu8Buffer)
{
    FILE * file_fd;
    I32 FileSize;

    file_fd = NULL;
    file_fd = fopen(pchFileName, "rb");
    if (file_fd == NULL)
    {
        printf("### fopen fail!");
        return -1;
    }
    fseek(file_fd, 0, SEEK_END);
    FileSize = ftell(file_fd);
    fseek(file_fd, 0, SEEK_SET);
    FileSize = fread(pu8Buffer, 1, FileSize, file_fd);
    if (FileSize == -1)
    {
        fclose(file_fd);
        printf("### fread fail!");
        return -1;
    }
    fclose(file_fd);

    return FileSize;
}

static int s_TempLoopFlag;

#define ADDR_READSENSOR             0x2000
#define ADDR_SENSORDEVICE           0x2002
#define ADDR_LED_1                      0x2003

// function from
extern  void begin(uint8_t);
extern  uint8_t  readInputRegisters(uint16_t, uint8_t);
extern  uint8_t  writeSingleRegister(uint16_t, uint16_t);
extern  uint8_t readHoldingRegisters(uint16_t, uint16_t);
extern  uint8_t calibrateRegister(uint16_t, uint8_t);
extern  uint8_t resetenergyRegister(uint16_t, uint8_t);
extern  uint8_t  writeSingleCoil(uint16_t, uint8_t);
extern  uint8_t readCoils(uint16_t, uint16_t);

uint8_t OpenDevice(uint8_t id)
{
    begin(id);
    return( writeSingleCoil(ADDR_SENSORDEVICE, 1));
}

uint8_t ReadDevice(uint8_t id)
{
    begin(id);
    return(readInputRegisters(ADDR_READSENSOR, 2));
}

uint8_t DeviceLedOn(uint8_t id)
{
    begin(id);
    return(writeSingleCoil(ADDR_LED_1,1));
}


uint8_t DeviceLedOff(uint8_t id)
{
    begin(id);
    return(writeSingleCoil(ADDR_LED_1,0));
}

static int _SliderSkinTempMenu(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    WM_HWIN hWin;

    hWin = pDrawItemInfo->hWin;

    switch (pDrawItemInfo->Cmd)
    {
    case WIDGET_ITEM_DRAW_BACKGROUND:
        break;
    case WIDGET_ITEM_DRAW_BITMAP:
        break;
    }
    return 0;
}

static void _cbTempMenu(WM_MESSAGE * pMsg) {
  WM_HWIN    hWin;
      WM_HWIN    hItem;
  int        Id;
  int        NCode;
    U32 FileSize;
    static WM_HWIN hImageTempMenu;
    static int TempFlag;

  hWin = pMsg->hWin;
  switch (pMsg->MsgId) {
  case WM_CREATE:
      AnimData1.Dir  = 0;
      AnimData1.hWin = hWin;
        //
        //
        //
        hImageTempMenu = IMAGE_CreateEx(0, 0, 256, 256, hWin, WM_CF_SHOW, 0, GUI_ID_IMAGE0);
        FileSize = NVT_Load_File("/mnt/dta/cool1_256x256.dta", s_au8Menu1);
        IMAGE_SetDTA(hImageTempMenu, s_au8Menu1, FileSize);
        //
        // SLIDER
        //
        hItem = SLIDER_CreateEx(0, 0, 256, 256, hWin, WM_CF_SHOW, 0, GUI_ID_SLIDER0);
        SLIDER_SetSkin(hItem, _SliderSkinTempMenu);
        //
        // Create timer
        //
        WM_CreateTimer(hWin, 3, 1000, 0);
    break;
    case WM_TIMER:
        if (s_TempLoopFlag == 1)
        {
            if (TempFlag == 0)
                FileSize = NVT_Load_File("/mnt/dta/dehumidify1_256x256.dta", s_au8Menu1);
            else
                FileSize = NVT_Load_File("/mnt/dta/dehumidify1.dta", s_au8Menu1);
            IMAGE_SetDTA(hImageTempMenu, s_au8Menu1, FileSize);
        }
        else if (s_TempLoopFlag == 2)
        {
            if (TempFlag == 0)
                FileSize = NVT_Load_File("/mnt/dta/fan1_256x256.dta", s_au8Menu1);
            else
                FileSize = NVT_Load_File("/mnt/dta/fan1.dta", s_au8Menu1);
            IMAGE_SetDTA(hImageTempMenu, s_au8Menu1, FileSize);
        }
        else if (s_TempLoopFlag == 3)
        {
            if (TempFlag == 0)
                FileSize = NVT_Load_File("/mnt/dta/heat1_256x256.dta", s_au8Menu1);
            else
                FileSize = NVT_Load_File("/mnt/dta/heat1.dta", s_au8Menu1);
            IMAGE_SetDTA(hImageTempMenu, s_au8Menu1, FileSize);
        }
        else
        {
            if (TempFlag == 0)
                FileSize = NVT_Load_File("/mnt/dta/cool1_256x256.dta", s_au8Menu1);
            else
                FileSize = NVT_Load_File("/mnt/dta/cool1.dta", s_au8Menu1);
            IMAGE_SetDTA(hImageTempMenu, s_au8Menu1, FileSize);
        }

        //WM_InvalidateRect(hWin, &s_Rect);
        WM_RestartTimer(pMsg->Data.v, 1000);
        break;
  //case WM_PAINT:
    //GUI_SetBkColor(GUI_YELLOW);
    //GUI_Clear();
    //break;
  case MSG_ANIMATE1:
      if (AnimData1.Dir != pMsg->Data.v) {
      _AnimateCreate1(&hAnim1, &AnimData1);
    }
    break;
  case WM_DELETE:
    break;
  case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case GUI_ID_SLIDER0: // Notifications sent by 'DateLevel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            TempFlag ^= 1;
            if (SettingModbusFlag)
            {
                if (TempFlag == 1)
                    DeviceLedOn(2);
                else
                    DeviceLedOff(2);
            }

        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  }
}

static int _SliderSkinDateMenu(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    WM_HWIN hWin;

    hWin = pDrawItemInfo->hWin;

    switch (pDrawItemInfo->Cmd)
    {
    case WIDGET_ITEM_DRAW_BACKGROUND:
        break;
    case WIDGET_ITEM_DRAW_BITMAP:
        break;
    }
    return 0;
}

static char s_buf1[64];

static void _cbDateMenu(WM_MESSAGE * pMsg) {
  WM_HWIN    hWin;
    WM_HWIN hItem;
  int        Id;
  int        NCode;
    U32 FileSize;
    FILE *pstream;
    char buf[3];
    static int DateFlag;
    static WM_HWIN hItemr;

  hWin = pMsg->hWin;
  switch (pMsg->MsgId) {
  case WM_CREATE:
        DateFlag = 0;

      AnimData2.Dir  = 0;
      AnimData2.hWin = hWin;
        //
        //
        //
        hItem = IMAGE_CreateEx(0, 0, 256, 256, hWin, WM_CF_SHOW, 0, GUI_ID_IMAGE0);
        FileSize = NVT_Load_File("/mnt/dta/date_menu.dta", s_au8Menu2);
        IMAGE_SetDTA(hItem, s_au8Menu2, FileSize);
        //
    // Initialization of 'DateTime'
    //
        hItem = TEXT_CreateEx(0, 0, 256, 128, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT0, NULL);
    TEXT_SetFont(hItem, GUI_FONT_D32);
    TEXT_SetText(hItem, "23:59");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    //
    //
    hItemr = TEXT_CreateEx(192, 0, 64, 32, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT4, NULL);
    TEXT_SetFont(hItemr, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItemr, "");
    TEXT_SetTextAlign(hItemr, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItemr, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'DateWeek'
    //
    hItem = TEXT_CreateEx(0, 136, 256, 40, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT1, NULL);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Wed");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'DateDate'
    //
    hItem = TEXT_CreateEx(0, 176, 256, 40, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT2, NULL);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "Aug 29");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'DateYear'
    //
    hItem = TEXT_CreateEx(0, 216, 256, 40, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT3, NULL);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "2020");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
        //
        // SLIDER
        //
        hItem = SLIDER_CreateEx(0, 0, 256, 256, hWin, WM_CF_SHOW, 0, GUI_ID_SLIDER0);
        SLIDER_SetSkin(hItem, _SliderSkinDateMenu);
        //
        // Create timer
        //
        WM_CreateTimer(hWin, 1, 1000, 0);
    break;
    case WM_TIMER:
        memset(s_buf1, 0x00, 40);
        hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT0);
        if (DateFlag == 0)
        {
            pstream = popen("date '+%T'", "r");
            //TEXT_SetFont(hItem, GUI_FONT_D32);
            fread(s_buf1, 1, 40, pstream);
            TEXT_SetText(hItemr, "");
        }
        else
        {
            pstream = popen("date '+%r'", "r");
            //TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
            fread(s_buf1, 1, 40, pstream);
            s_buf1[11] = 0x00;
            buf[0] = s_buf1[9];
            buf[1] = s_buf1[10];
            buf[2] = s_buf1[11];
            TEXT_SetText(hItemr, buf);
            s_buf1[8] = 0x00;
            s_buf1[9] = 0x00;
            s_buf1[10] = 0x00;
        }
        //fread(s_buf1, 1, 40, pstream);
        pclose(pstream);
        TEXT_SetText(hItem, s_buf1);

        memset(s_buf1, 0x00, 40);
        pstream = popen("date '+%a'", "r");
        fread(s_buf1, 1, 40, pstream);
        pclose(pstream);
        hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT1);
        TEXT_SetText(hItem, s_buf1);

        memset(s_buf1, 0x00, 40);
        pstream = popen("date '+%b %d'", "r");
        fread(s_buf1, 1, 40, pstream);
        pclose(pstream);
        hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT2);
        TEXT_SetText(hItem, s_buf1);

        memset(s_buf1, 0x00, 40);
        pstream = popen("date '+%Y'", "r");
        fread(s_buf1, 1, 40, pstream);
        pclose(pstream);
        hItem = WM_GetDialogItem(hWin, GUI_ID_TEXT3);
        TEXT_SetText(hItem, s_buf1);

        //WM_InvalidateRect(hWin, &s_Rect);
        WM_RestartTimer(pMsg->Data.v, 1000);
        break;
  //case WM_PAINT:
    //GUI_SetBkColor(GUI_RED);
    //GUI_Clear();
    //break;
  case MSG_ANIMATE2:
      if (AnimData2.Dir != pMsg->Data.v) {
      _AnimateCreate2(&hAnim2, &AnimData2);
    }
    break;
  case WM_DELETE:
    break;
  case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case GUI_ID_SLIDER0: // Notifications sent by 'DateLevel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            DateFlag ^= 1;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  }
}

static int _SliderSkinWeatherMenu(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    WM_HWIN hWin;

    hWin = pDrawItemInfo->hWin;

    switch (pDrawItemInfo->Cmd)
    {
    case WIDGET_ITEM_DRAW_BACKGROUND:
        break;
    case WIDGET_ITEM_DRAW_BITMAP:
        break;
    }
    return 0;
}

int g_WeatherFlag;
static char s_buf3[2 * 1024];
static char s_buf3a[2 * 1024];
static char s_buf3b[1 * 1024];
extern char g_au8CITY[];
static char g_au8CITYWeather[1024];

static void _cbWeatherMenu(WM_MESSAGE * pMsg) {
  WM_HWIN    hWin;
    WM_HWIN hItem;
  int        Id;
  int        NCode;
    U32 FileSize;
    FILE *pstream;
    int i, j, k;
    static WM_HWIN hWinWeatherWeather;
    static WM_HWIN hTextWeatherCity;
    static WM_HWIN hTemp1;
    static WM_HWIN hTemp2;
    static WM_HWIN hTempF1;
    static WM_HWIN hTempF2;

  hWin = pMsg->hWin;
  switch (pMsg->MsgId) {
  case WM_CREATE:
      AnimData3.Dir  = 0;
      AnimData3.hWin = hWin;
        //sprintf(g_au8CITY, "%s", "hsinchu");
        //
        //
        //
        hItem = IMAGE_CreateEx(0, 0, 256, 256, hWin, WM_CF_SHOW, 0, GUI_ID_IMAGE0);
        FileSize = NVT_Load_File("/mnt/dta/weather_menu.dta", s_au8Menu3);
        IMAGE_SetDTA(hItem, s_au8Menu3, FileSize);
        //
    // Initialization of 'WeatherCity'
    //
    hTextWeatherCity = TEXT_CreateEx(0, 0, 256, 40, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT1, NULL);
    TEXT_SetFont(hTextWeatherCity, GUI_FONT_32B_ASCII);
    TEXT_SetText(hTextWeatherCity, "HsinChu");
    TEXT_SetTextAlign(hTextWeatherCity, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hTextWeatherCity, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'WeatherTemp'
    //
    hTemp1 = TEXT_CreateEx(0, 40, 128, 60, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT0, NULL);
    TEXT_SetFont(hTemp1, GUI_FONT_D48);
    TEXT_SetText(hTemp1, "35");
    TEXT_SetTextAlign(hTemp1, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hTemp1, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'WeatherTemp2'
    //
    hTemp2 = TEXT_CreateEx(128, 40, 128, 60, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT0, NULL);
    TEXT_SetFont(hTemp2, GUI_FONT_32B_1);
    s_buf3a[0] = 0xB0; s_buf3a[1] = 'C'; s_buf3a[2] = 0x00;
    TEXT_SetText(hTemp2, s_buf3a);
    TEXT_SetTextAlign(hTemp2, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hTemp2, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'WeatherFeelTemp'
    //
    hTempF1 = TEXT_CreateEx(0, 100, 128, 60, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT0, NULL);
    TEXT_SetFont(hTempF1, GUI_FONT_D48);
    TEXT_SetText(hTempF1, "40");
    TEXT_SetTextAlign(hTempF1, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hTempF1, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'WeatherWeather'
    //
    //hItem = IMAGE_CreateEx(8, 50, 32, 32, hWin, WM_CF_SHOW, 0, GUI_ID_IMAGE0);
    //pData = _GetImageById(ID_IMAGE_0_IMAGE_0, &FileSize);
    //IMAGE_SetBMP(hItem, pData, FileSize);
    //
    // Initialization of 'WeatherFeelTemp2'
    //
    hTempF2 = TEXT_CreateEx(128, 100, 128, 60, hWin, WM_CF_SHOW, 0, GUI_ID_TEXT0, NULL);
    TEXT_SetFont(hTempF2, GUI_FONT_32B_1);
    sprintf(s_buf3a, "%s", ".C Feels");
    s_buf3a[0] = 0xB0;
    TEXT_SetText(hTempF2, s_buf3a);
    TEXT_SetTextAlign(hTempF2, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hTempF2, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'WeatherWeather2'
    //
    hWinWeatherWeather = IMAGE_CreateEx(12, 166, 232, 84, hWin, WM_CF_SHOW, 0, GUI_ID_IMAGE1);
    //hWinWeatherWeather = IMAGE_CreateEx(12, 86, 232, 84, hWin, WM_CF_SHOW, 0, GUI_ID_IMAGE1);
    FileSize = NVT_Load_File("/mnt/png/w1.png", s_au8WeatherWeather);
    IMAGE_SetPNG(hWinWeatherWeather, s_au8WeatherWeather, FileSize);
    //
        // SLIDER
        //
        hItem = SLIDER_CreateEx(0, 0, 256, 256, hWin, WM_CF_SHOW, 0, GUI_ID_SLIDER0);
        SLIDER_SetSkin(hItem, _SliderSkinWeatherMenu);
        //
        // Create timer
        //
        //WM_CreateTimer(hWin, 2, 600000, 0);
        WM_CreateTimer(hWin, 2, 60000, 0);
    break;
    case WM_TIMER:
        // FIXME
        printf("### g_au8CITY=%s ###\n", g_au8CITY);
        TEXT_SetText(hTextWeatherCity, g_au8CITY);
#if 1
        memset(s_buf3, 0x00, 2*1024);
        sprintf(g_au8CITYWeather, "curl http://wttr.in/%s?0T", g_au8CITY);
        pstream = popen(g_au8CITYWeather, "r");
        fread(s_buf3, 1, 2*1024, pstream);
        //printf("### %s ###\n", s_buf3);
        pclose(pstream);
        //for (i = 0; i < 2 * 1024; i++)
        //{
            //if (s_buf3[i] == 0x00)
                //break;
            //else
                //printf("%c ", s_buf3[i]);
        //}
#if 1
        j = 0;
        for (i = 0; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x3A)
            {
                s_buf3a[j] = 0x00;
                if (strcmp("Weather report", s_buf3a) == 0)
                {
                    printf("### marker found %s ###\n", s_buf3a);
                    break;
                }
                else
                {
                    WM_RestartTimer(pMsg->Data.v, 60000);
                    printf("### marker not found %s ###\n", s_buf3a);
                    return;
                }
            }
            else
            {
                s_buf3a[j] = s_buf3[i];
                j++;
            }
        }
#endif
#if 1
        i++;
        if (s_buf3[i] == 0x20)
        {
            printf("### marker2 found ###\n");
        }
        else
        {
            WM_RestartTimer(pMsg->Data.v, 60000);
            printf("### marker2 not found ###\n");
            return;
        }
        i++;
        j = 0;
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                s_buf3a[j] = 0x00;
                printf("### city=%s ###\n", s_buf3a);
                break;
            }
            else
            {
                s_buf3a[j] = s_buf3[i];
                j++;
            }
        }
#endif
#if 1
        i++;
        if (s_buf3[i] == 0x0A)
        {
            printf("### marker3 found ###\n");
        }
        else
        {
            WM_RestartTimer(pMsg->Data.v, 60000);
            printf("### marker3 not found ###\n");
            return;
        }
        i=i+17;
        j = 0;
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                s_buf3a[j] = 0x00;
                printf("### type=%s ###\n", s_buf3a);
                break;
            }
            else
            {
                s_buf3a[j] = s_buf3[i];
                j++;
            }
        }
#endif
#if 1
        i=i+17;
        j = 0;
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                //s_buf3a[j] = 0x00;
                //printf("### degree1=%s ###\n", s_buf3a);
                break;
            }
            else
            {
                s_buf3a[j] = s_buf3[i];
                if ((s_buf3a[j] == 0x2E) || (s_buf3a[j] == 0x20))
                {
                    s_buf3a[j] = 0x00;
                    TEXT_SetText(hTemp1, s_buf3a);
                    j = 0;
                    s_buf3a[j] = 0xB0;
                    j++;
                    s_buf3a[j] = 'C';
                    j++;
                    s_buf3a[j] = 0x00;
                    TEXT_SetText(hTemp2, s_buf3a);
                    break;
                }
                else
                    j++;
            }
        }
        if ((s_buf3[i] == 0x20) && (s_buf3[i + 1] == 0xC2) && (s_buf3[i + 2] == 0xB0) && (s_buf3[i + 3] == 0x43))
        {
            TEXT_GetText(hTemp2, s_buf3a, 16);
            j = 2;
            s_buf3a[j] = ' ';
            j++;
            s_buf3a[j] = 'F';
            j++;
            s_buf3a[j] = 'e';
            j++;
            s_buf3a[j] = 'e';
            j++;
            s_buf3a[j] = 'l';
            j++;
            s_buf3a[j] = 's';
            j++;
            s_buf3a[j] = 0x00;
            TEXT_SetText(hTempF2, s_buf3a);
            TEXT_GetText(hTemp1, s_buf3a, 16);
            TEXT_SetText(hTempF1, s_buf3a);
        }
        else
        {
        i=i+2;
        j = 0;
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                //s_buf3a[j] = 0x00;
                //printf("### degree2=%s ###\n", s_buf3a);
                break;
            }
            else
            {
                s_buf3a[j] = s_buf3[i];
                if (s_buf3a[j] == 0x20)
                {
                    s_buf3a[j] = 0x00;
                    TEXT_SetText(hTempF1, s_buf3a);
                    j = 0;
                    s_buf3a[j] = 0xB0;
                    j++;
                    s_buf3a[j] = 'C';
                    j++;
                    s_buf3a[j] = ' ';
                    j++;
                    s_buf3a[j] = 'F';
                    j++;
                    s_buf3a[j] = 'e';
                    j++;
                    s_buf3a[j] = 'e';
                    j++;
                    s_buf3a[j] = 'l';
                    j++;
                    s_buf3a[j] = 's';
                    j++;
                    s_buf3a[j] = 0x00;
                    TEXT_SetText(hTempF2, s_buf3a);
                    break;
                }
                else
                    j++;
            }
        }
        }
#endif
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                break;
            }
        }
        i=i+17;
        j = 0;
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                s_buf3a[j] = 0x00;
                printf("### 1=%x %x %x %x ", s_buf3a[0], s_buf3a[1], s_buf3a[2], s_buf3a[3]);
                printf("1=%s ###\n", s_buf3a);
                break;
            }
            else
            {
                s_buf3a[j] = s_buf3[i];
                j++;
            }
        }
        i=i+17;
        j = i;
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                //s_buf3a[j] = 0x00;
                j--;
                while (j != 0)
                {
                    if (s_buf3[j] == 0x20)
                    {
                        j--;
                    }
                    else
                    {
                        if ((s_buf3[j] == 0x6D) && (s_buf3[j - 1] == 0x6B) && (s_buf3[j - 2] == 0x20))
                            break;
                    }
                }
                j-=3;
                while (j != 0)
                {
                    if (s_buf3[j] != 0x20)
                    {
                        j--;
                    }
                    else
                    {
                        break;
                    }
                }
                j++;
                k = 0;
                while(1)
                {
                    if (s_buf3[j] == 0x0A)
                    {
                        s_buf3a[k] = 0x00;
                        break;
                    }
                    else
                    {
                        s_buf3a[k] = s_buf3[j];
                        k++;
                        j++;
                    }
                }
                printf("### 2=%s ###\n", s_buf3a);
                break;
            }
            //else
            //{
                //s_buf3a[j] = s_buf3[i];
                //j++;
            //}
            j++;
        }
        i=i+17;
        j = i;
        for (; i < 2 * 1024; i++)
        {
            if (s_buf3[i] == 0x0A)
            {
                //s_buf3a[j] = 0x00;
                j--;
                while (j != 0)
                {
                    if (s_buf3[j] == 0x20)
                    {
                        j--;
                    }
                    else
                    {
                        if ((s_buf3[j] == 0x6D) && (s_buf3[j - 1] == 0x6D) && (s_buf3[j - 2] == 0x20))
                            break;
                    }
                }
                j-=3;
                while (j != 0)
                {
                    if (s_buf3[j] != 0x20)
                    {
                        j--;
                    }
                    else
                    {
                        break;
                    }
                }
                j++;
                k = 0;
                while(1)
                {
                    if (s_buf3[j] == 0x0A)
                    {
                        s_buf3a[k] = 0x00;
                        break;
                    }
                    else
                    {
                        s_buf3a[k] = s_buf3[j];
                        k++;
                        j++;
                    }
                }
                printf("### 3=%s ###\n", s_buf3a);
                break;
            }
            //else
            //{
                //s_buf3a[j] = s_buf3[i];
                //j++;
            //}
            j++;
        }
#endif
        //memset(s_buf3, 0x00, 2 * 1024);
        sprintf(g_au8CITYWeather, "curl http://wttr.in/%s_0q.png --output /tmp/w1.png", g_au8CITY);
        //pstream = popen("curl http://wttr.in/hsinchu_0q.png --output /mnt/png/w1.png", "r");
        pstream = popen(g_au8CITYWeather, "r");
        //fread(s_buf3, 1, 2 * 1024, pstream);
        //printf("### %s ###\n", s_buf3);
        pclose(pstream);

        //memset(s_buf3, 0x00, 2 * 1024);
        sprintf(g_au8CITYWeather, "curl http://wttr.in/%s_3Fq.png --output /tmp/w2.png", g_au8CITY);
        //pstream = popen("curl http://wttr.in/hsinchu_3Fq.png --output /mnt/png/w2.png", "r");
        pstream = popen(g_au8CITYWeather, "r");
        //fread(s_buf3, 1, 2 * 1024, pstream);
        //printf("### %s ###\n", s_buf3);
        pclose(pstream);

        FileSize = NVT_Load_File("/tmp/w1.png", s_au8WeatherWeather);
        IMAGE_SetPNG(hWinWeatherWeather, s_au8WeatherWeather, FileSize);
        //WM_InvalidateRect(hWin, &s_Rect);
        //WM_RestartTimer(pMsg->Data.v, 600000);
        WM_RestartTimer(pMsg->Data.v, 60000);
        break;
  //case WM_PAINT:
    //GUI_SetBkColor(GUI_GREEN);
    //GUI_Clear();
    //break;
  case MSG_ANIMATE3:
      if (AnimData3.Dir != pMsg->Data.v) {
      _AnimateCreate3(&hAnim3, &AnimData3);
    }
    break;
  case WM_DELETE:
    break;
  case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case GUI_ID_SLIDER0: // Notifications sent by 'WeatherLevel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            g_WeatherFlag = 1;
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  }
}

static int _ButtonSkin(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    int Index;
    WM_HWIN hWin;

    hWin = pDrawItemInfo->hWin;
    BUTTON_GetUserData(hWin, &Index, sizeof(Index));

    switch (pDrawItemInfo->Cmd)
    {
    case WIDGET_ITEM_DRAW_BACKGROUND:
//        GUI_SetBkColor(0x00ABBCC5);
        //GUI_SetBkColor(GUI_YELLOW);
        //GUI_Clear();
        break;
    case WIDGET_ITEM_DRAW_BITMAP:
        if (Index == 1)
            NVT_Load_File2("/mnt/dta/down1.dta", 0, 0);
        else if (Index == 2)
            NVT_Load_File2("/mnt/dta/up1.dta", 0, 0);
        break;
    }
    return 0;
}

extern int c_div, c_rem, f_div, f_rem;

static char s_achT1[] =
{
    '2', '3', 0
};
static char s_achT2[] =
{
    '.', '5', 0xB0, 'C', 0
};

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
    int i;
    FILE *pstream;
  WM_MESSAGE Message1;
  WM_MESSAGE Message2;
  WM_MESSAGE Message3;
  static int win1flag;
  static int win2flag;
  static int win3flag;
  static int wincounter;
    static int s_MainMenuFlag;
    //static int s_ledFlag;

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    FileSize = NVT_Load_File("/mnt/dta/main_menu.dta", s_au8MainMenu);
    IMAGE_SetDTA(hItem, s_au8MainMenu, FileSize);
    //
    // Initialization of 'Heading'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
    FileSize = NVT_Load_File("/mnt/dta/logo.dta", s_au8Heading);
    IMAGE_SetDTA(hItem, s_au8Heading, FileSize);
    //
    // Initialization of 'WiFi'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
    FileSize = NVT_Load_File("/mnt/png/wifi_off.png", s_au8WiFi);
    IMAGE_SetPNG(hItem, s_au8WiFi, FileSize);
    //
    // Initialization of 'Eth'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
    FileSize = NVT_Load_File("/mnt/png/eth_off.png", s_au8Eth);
    IMAGE_SetPNG(hItem, s_au8Eth, FileSize);
    //
    // Initialization of 'Temp1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_D48);
    TEXT_SetText(hItem, "23");
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Temp2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    TEXT_SetText(hItem, "");
    //
    // Initialization of 'IP1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'IP2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    TEXT_SetText(hItem, "");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    // USER START (Optionally insert additional code for further widget initialization)
    sprintf(g_au8CITY, "%s", "hsinchu");

    hTempMenu = WM_CreateWindowAsChild(8, 480, 256, 256, pMsg->hWin, WM_CF_SHOW | WM_CF_STAYONTOP, _cbTempMenu, 0);
    hDateMenu = WM_CreateWindowAsChild(272, 480, 256, 256, pMsg->hWin, WM_CF_SHOW | WM_CF_STAYONTOP, _cbDateMenu, 0);
    hWeatherMenu = WM_CreateWindowAsChild(536, 480, 256, 256, pMsg->hWin, WM_CF_SHOW | WM_CF_STAYONTOP, _cbWeatherMenu, 0);
    WM_CreateTimer(pMsg->hWin, 0, 500, 0);

        i = 1;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &i, sizeof(i));

        i = 2;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &i, sizeof(i));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetText(hItem, s_achT2);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Temp-'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Temp+'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'TempLoop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            s_TempLoopFlag++;
            if (s_TempLoopFlag == 1)
            {
                ;
            }
            else if (s_TempLoopFlag == 2)
            {
                ;
            }
            else if (s_TempLoopFlag == 3)
            {
                ;
            }
            else
            {
                s_TempLoopFlag = 0;
            }
#if 0
            if (SettingModbusFlag)
            {
                s_ledFlag ^= 1;
                if (s_ledFlag == 1)
                    DeviceLedOn(1);
                else
                    DeviceLedOff(1);
            }
#endif
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Setting'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            g_SettingFlag = 1;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  case WM_TIMER:
        if (s_MainMenuFlag == 0)
        {
            //WM_Invalidate(pMsg->hWin);
            WM_RestartTimer(pMsg->Data.v, 0);
            if (win1flag == 0)
            {
                win1flag = 1;
            Message1.Data.v = 1;  // 1 stand for show TempMenu
          Message1.hWin   = hTempMenu;
          Message1.MsgId  = MSG_ANIMATE1;
          WM_SendMessage(hTempMenu, &Message1);
            }
            if (win2flag == 0 && wincounter >= 2)
            {
                win2flag = 1;
            Message2.Data.v = 1;  // 1 stand for show DateMenu
          Message2.hWin   = hDateMenu;
          Message2.MsgId  = MSG_ANIMATE2;
          WM_SendMessage(hDateMenu, &Message2);
            }
            if (win3flag == 0 && wincounter >= 3)
            {
                win3flag = 1;
            Message3.Data.v = 1;  // 1 stand for show WeatherMenu
          Message3.hWin   = hWeatherMenu;
          Message3.MsgId  = MSG_ANIMATE3;
          WM_SendMessage(hWeatherMenu, &Message3);
                s_MainMenuFlag = 1;
                WM_RestartTimer(pMsg->Data.v, 5000);
            }
            wincounter++;
            //WM_RestartTimer(pMsg->Data.v, 0);
        }
        else
        {
            WM_RestartTimer(pMsg->Data.v, 5000);
            if (SettingWiFiFlag == 0)
            {
                hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
                FileSize = NVT_Load_File("/mnt/png/wifi_off.png", s_au8WiFi);
                IMAGE_SetPNG(hItem, s_au8WiFi, FileSize);

                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
                TEXT_SetText(hItem, "");
            }
            else
            {
                memset(s_buf0, 0x00, 1024);
                pstream = popen("wpa_cli -i wlan0 status|grep ip_address=|cut -f2 -d=", "r");
                fread(s_buf0, 1, 1024, pstream);
                printf("### wip=%s ###\n", s_buf0);
                pclose(pstream);

                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
                TEXT_SetText(hItem, s_buf0);

                memset(s_buf0, 0x00, 1024);
                pstream = popen("wpa_cli -i wlan0 signal_poll|grep RSSI=|cut -f2 -d=", "r");
                fread(s_buf0, 1, 1024, pstream);
                printf("### RSSI=%s ", s_buf0);
                pclose(pstream);

                if (s_buf0[1] <= 0x34)
                {
                    printf("3 ");
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
                    FileSize = NVT_Load_File("/mnt/png/wifi_3.png", s_au8WiFi);
                    IMAGE_SetPNG(hItem, s_au8WiFi, FileSize);
                }
                else if (s_buf0[1] <= 0x36)
                {
                    printf("2 ");
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
                    FileSize = NVT_Load_File("/mnt/png/wifi_2.png", s_au8WiFi);
                    IMAGE_SetPNG(hItem, s_au8WiFi, FileSize);
                }
                else if (s_buf0[1] <= 0x38)
                {
                    printf("1 ");
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
                    FileSize = NVT_Load_File("/mnt/png/wifi_1.png", s_au8WiFi);
                    IMAGE_SetPNG(hItem, s_au8WiFi, FileSize);
                }
                else
                {
                    printf("0 ");
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
                    FileSize = NVT_Load_File("/mnt/png/wifi_0.png", s_au8WiFi);
                    IMAGE_SetPNG(hItem, s_au8WiFi, FileSize);
                }
                printf("###\n");
            }
            if (SettingEthernetFlag == 0)
            {
                hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
                FileSize = NVT_Load_File("/mnt/png/eth_off.png", s_au8Eth);
                IMAGE_SetPNG(hItem, s_au8Eth, FileSize);

                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
                TEXT_SetText(hItem, "");
            }
            else
            {
                hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
                FileSize = NVT_Load_File("/mnt/png/eth_on.png", s_au8Eth);
                IMAGE_SetPNG(hItem, s_au8Eth, FileSize);

                memset(s_buf0, 0x00, 1024);
                pstream = popen("ifconfig eth0|grep addr:|cut -f2 -d:", "r");
                fread(s_buf0, 1, 1024, pstream);
                for (i = 0; i < 1024; i++)
                {
                    if (s_buf0[i] == 0x20)
                    {
                        s_buf0[i] = 0x00;
                        break;
                    }
                }
                printf("### eip=%s ###\n", s_buf0);
                pclose(pstream);

                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
                TEXT_SetText(hItem, s_buf0);
            }
            #if 0 // FIXME
            memset(g_buf0, 0x00, 4*1024);
            pstream = popen("wpa_cli -i wlan0 scan_results", "r");
            fread(g_buf0, 1, 4*1024, pstream);
            printf("### sr=%s ###\n", g_buf0);
            pclose(pstream);
            #endif
            if (SettingModbusFlag == 2)
            {
                SettingModbusFlag = 2;
                ReadDevice(2);
                sprintf(s_achT1, "%02d", c_div);
                sprintf(s_achT2, ".%01d", c_rem);
                s_achT2[2] = 0xB0;
                s_achT2[3] = 'C';
                s_achT2[4] = 0;
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
                TEXT_SetText(hItem, s_achT1);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
                TEXT_SetText(hItem, s_achT2);
            }
            if (SettingModbusFlag == 1)
            {
                SettingModbusFlag = 2;
                OpenDevice(2);
            }
        }
            break;

  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
extern WM_HWIN CreateWeatherMenu2(void);
static WM_HWIN s_hWinWeather2;

extern WM_HWIN CreateSettingMenu(void);
static WM_HWIN s_hWinSetting;

extern int GUI_VNC_X_StartServer(int LayerIndex, int ServerIndex);

extern int rs485_main(void);

char g_Menu2Temp1Voltage[20];
char g_Menu2Temp1Current[20];
char g_Menu2Temp1Power[20];
char g_Menu2Temp1Energy[20];

void MainTask2(void)
{
    rs485_main();

    WM_SetCreateFlags(WM_CF_MEMDEV);
    GUI_Init();
    WM_MULTIBUF_Enable(1);
    GUI_MEMDEV_MULTIBUF_Enable(1);
    CreateWindow();
    while (1)
    {
        GUI_Delay(100);
        if (g_WeatherFlag == 1)
        {
            g_WeatherFlag = 0;
            s_hWinWeather2 = CreateWeatherMenu2();
        }
        if (g_WeatherFlag == 2)
        {
            g_WeatherFlag = 0;
            WM_DeleteWindow(s_hWinWeather2);
        }
        if (g_SettingFlag == 1)
        {
            g_SettingFlag = 0;
            s_hWinSetting = CreateSettingMenu();
        }
        if (g_SettingFlag == 2)
        {
            g_SettingFlag = 0;
            WM_DeleteWindow(s_hWinSetting);
        }
        if (SettingVNCFlag == 1)
        {
            SettingVNCFlag = 2;
            GUI_VNC_X_StartServer(0, 0);
        }
    }
}

// USER END

/*************************** End of file ****************************/


