/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.48                          *
*        Compiled Jun 13 2018, 10:51:02                              *
*        (c) 2018 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_BUTTON_0   (GUI_ID_USER + 0x09)
#define ID_BUTTON_1   (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2   (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3   (GUI_ID_USER + 0x0C)
#define ID_BUTTON_4   (GUI_ID_USER + 0x0D)
#define ID_BUTTON_5   (GUI_ID_USER + 0x0E)
#define ID_BUTTON_6   (GUI_ID_USER + 0x0F)
#define ID_BUTTON_7   (GUI_ID_USER + 0x10)


// USER START (Optionally insert additional defines)
#define NVT_MOVE_1 "DCIM/mu20_menu1a.mp4"
#define NVT_MOVE_2 "DCIM/mu20_menu2a.mp4"
#define NVT_MOVE_3 "DCIM/mu20_menu3a.mp4"
#define NVT_MOVE_4 "DCIM/mu20_menu4a.mp4"
#define NVT_MOVE_5 "DCIM/mu20_menu5a.mp4"
#define NVT_MOVE_6 "DCIM/mu20_menu6a.mp4"

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern U32 g_u32InCookingMenu;

extern void NVT_PlayFile(const char * FileName);

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window_Cooking", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button1", ID_BUTTON_0, 0, 0, 200, 240, 0, 0x0, 1 },
  { BUTTON_CreateIndirect, "Button2", ID_BUTTON_1, 200, 0, 200, 240, 0, 0x0, 2 },
  { BUTTON_CreateIndirect, "Button3", ID_BUTTON_2, 400, 0, 200, 240, 0, 0x0, 3 },
  { BUTTON_CreateIndirect, "Button4", ID_BUTTON_3, 600, 0, 200, 240, 0, 0x0, 4 },
  { BUTTON_CreateIndirect, "Button5", ID_BUTTON_4, 0, 240, 200, 240, 0, 0x0, 5 },
  { BUTTON_CreateIndirect, "Button6", ID_BUTTON_5, 200, 240, 200, 240, 0, 0x0, 6 },
  { BUTTON_CreateIndirect, "Button7", ID_BUTTON_6, 400, 240, 200, 240, 0, 0x0, 7 },
  { BUTTON_CreateIndirect, "Button8", ID_BUTTON_7, 600, 240, 200, 240, 0, 0x0, 8 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static int _ButtonSkin(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    int Index;
    WM_HWIN hWin, hWinBase;

    hWin = pDrawItemInfo->hWin;
    BUTTON_GetUserData(hWin, &Index, sizeof(Index));

    switch (pDrawItemInfo->Cmd)
    {
    case WIDGET_ITEM_DRAW_BACKGROUND:
        switch (Index)
        {
        case 1:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("01_dessert.dta", 0, 0);
            break;
        case 2:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("02_meat.dta", 0, 0);
            break;
        case 3:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("03_rice.dta", 0, 0);
            break;
        case 4:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("04_seafood.dta", 0, 0);
            break;
        case 5:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("05_soup.dta", 0, 0);
            break;
        case 6:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("06_vegetable.dta", 0, 0);
            break;
        case 7:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("07_temp_time.dta", 0, 0);
            break;
        case 8:
            //printf("## 0x%x\n", Index);
            NVT_IMG_Decode("08_setting.dta", 0, 0);
            break;
        }
        break;
    case WIDGET_ITEM_DRAW_BITMAP:
//        sysprintf("### 0x%x\n", Index);
        break;
    }

    return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
    int Index;

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window_Cooking'
    //
    //hItem = pMsg->hWin;
    //WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00F8F8F8));
    // USER START (Optionally insert additional code for further widget initialization)
        Index = 1;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 2;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 3;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 4;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 5;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 6;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 7;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 8;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_PlayFile(NVT_MOVE_1);
            g_u32InCookingMenu = 0;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_PlayFile(NVT_MOVE_2);
            g_u32InCookingMenu = 0;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_PlayFile(NVT_MOVE_3);
            g_u32InCookingMenu = 0;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_PlayFile(NVT_MOVE_4);
            g_u32InCookingMenu = 0;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_PlayFile(NVT_MOVE_5);
            g_u32InCookingMenu = 0;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_PlayFile(NVT_MOVE_6);
            g_u32InCookingMenu = 0;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Button7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            g_u32InCookingMenu = 7;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Button8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            g_u32InCookingMenu = 8;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow_Cooking
*/
WM_HWIN CreateWindow_Cooking(void);
WM_HWIN CreateWindow_Cooking(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
