/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH                         *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 6.10                          *
*        Compiled Dec 19 2019, 16:36:21                              *
*        (c) 2019 Segger Microcontroller GmbH                        *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0              (GUI_ID_USER + 0x00)
#define ID_BUTTON_0              (GUI_ID_USER + 0x01)
#define ID_BUTTON_1              (GUI_ID_USER + 0x03)
#define ID_BUTTON_2              (GUI_ID_USER + 0x04)
#define ID_BUTTON_3              (GUI_ID_USER + 0x05)
#define ID_SLIDER_0              (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static U32 g_ShowPlay;
static U32 g_ShowPause;
static U32 g_ShowHome;
static U32 g_ShowNext;
static U32 g_ShowPrevious;

extern U32 g_u32Playing;
extern U32 u64CurrentInPercent_Current_now;
extern void NVT_Home(void);
extern void NVT_PlayPause(void);
extern void NVT_GetPos(U32 Pos);
extern void NVT_IMG_Decode(char * szFileName, int x, int y);

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Play", ID_BUTTON_0, 368, 208, 64, 64, 0, 0x0, 1 },
  { BUTTON_CreateIndirect, "Home", ID_BUTTON_1, 64, 64, 64, 64, 0, 0x0, 2 },
  { BUTTON_CreateIndirect, "Next", ID_BUTTON_2, 700, 208, 64, 64, 0, 0x0, 3 },
  { BUTTON_CreateIndirect, "Previous", ID_BUTTON_3, 64, 208, 64, 64, 0, 0x0, 4 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 50, 331, 714, 126, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static int _ButtonSkin(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    int Index;
    WM_HWIN hWin;

    hWin = pDrawItemInfo->hWin;
    BUTTON_GetUserData(hWin, &Index, sizeof(Index));

    switch (pDrawItemInfo->Cmd)
    {
    case WIDGET_ITEM_DRAW_BACKGROUND:
        switch (Index)
        {
        case 1:
            if (g_ShowPlay == 1)
                NVT_IMG_Decode("Play_01.dta", 0, 0);

            if (g_ShowPause == 1)
                NVT_IMG_Decode("Pause_01.dta", 0, 0);
            break;
        case 2:
            if (g_ShowHome == 1)
                NVT_IMG_Decode("Home_01.dta", 0, 0);
            break;
        case 3:
            if (g_ShowNext == 1)
                NVT_IMG_Decode("Next_01.dta", 0, 0);
            break;
        case 4:
            if (g_ShowPrevious == 1)
                NVT_IMG_Decode("Previous_01.dta", 0, 0);
            break;
        }
        break;
    case WIDGET_ITEM_DRAW_BITMAP:
//        sysprintf("### 0x%x\n", Index);
        break;
    }

    return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
    int Index;
    U32 seek_pct;

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FF00FF));
    // USER START (Optionally insert additional code for further widget initialization)
        //hItem = pMsg->hWin;
        //WINDOW_SetBkColor(hItem, GUI_MAGENTA);

        Index = 1;
        g_ShowPlay = 0;
        g_ShowPause = 1;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 2;
        g_ShowHome = 1;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 3;
        g_ShowNext = 0;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));

        Index = 4;
        g_ShowPrevious = 0;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetSkin(hItem, _ButtonSkin);
        BUTTON_SetUserData(hItem, &Index, sizeof(Index));
        //
        // Set SLIDER width & range
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        SLIDER_SetWidth(hItem, 32);
        SLIDER_SetRange(hItem, 0, 100);
        //
        // Create timer
        //
        WM_CreateTimer(pMsg->hWin, 0, 1000, 0);

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Play'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_PlayPause();

            g_ShowPlay = !g_ShowPlay;
            g_ShowPause = !g_ShowPause;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Home'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            NVT_Home();
            g_u32Playing = 0;

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Next'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Previous'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
            seek_pct = SLIDER_GetValue(hItem);
            NVT_GetPos(seek_pct);

        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
    case WM_TIMER:
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        SLIDER_SetValue(hItem, u64CurrentInPercent_Current_now);
        //printf("%s\n", sBuf);
        //printf("%d\n", u64CurrentInPercent_Current_now);
        //WM_Invalidate(pMsg->hWin);
        WM_RestartTimer(pMsg->Data.v, 0);
        
        break;

  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
